EzpeletaNetCore8/Controllers/TipoEjerciciosController.cs
using Microsoft.AspNetCore.Mvc;
using EzpeletaNetCore8.Models;
using EzpeletaNetCore8.Data;
using Microsoft.AspNetCore.Authorization;
using System.Globalization;

namespace EzpeletaNetCore8.Controllers;

// [Authorize]
public class TipoEjerciciosController : Controller
{
    private ApplicationDbContext _context;

    //CONSTRUCTOR
    public TipoEjerciciosController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult Index()
    {
        return View();
    }

    public JsonResult ListadoTipoEjercicios(int? id)
    {
        //DEFINIMOS UNA VARIABLE EN DONDE GUARDAMOS EL LISTADO COMPLETO DE TIPOS DE EJERCICIOS
        var tipoDeEjercicios = _context.TipoEjercicios.ToList();

        //LUEGO PREGUNTAMOS SI EL USUARIO INGRESO UN ID
        //QUIERE DECIR QUE QUIERE UN EJERCICIO EN PARTICULAR
        if (id != null)
        {
            //FILTRAMOS EL LISTADO COMPLETO DE EJERCICIOS POR EL EJERCICIO QUE COINCIDA CON ESE ID
            tipoDeEjercicios = tipoDeEjercicios.Where(t => t.TipoEjercicioID == id).ToList();
        }

        return Json(tipoDeEjercicios);
    }

    public JsonResult GuardarTipoEjercicio(int tipoEjercicioID, string descripcion, string met)
    {
        //FIJAR INFORMACION DE CULTURA PARA FECHA Y DECIMALES
        Thread.CurrentThread.CurrentCulture = new CultureInfo("es-AR");

        if(!string.IsNullOrEmpty(met)){
            met = met.Replace(".", ",");
        }
        Decimal metDecimal = new Decimal();
        var validaMet = Decimal.TryParse(met, out metDecimal);
        //1- VERIFICAMOS SI REALMENTE INGRESO ALGUN CARACTER Y LA VARIABLE NO SEA NULL
        // if (descripcion != null && descripcion != "")
        // {
        //     //INGRESA SI ESCRIBIO SI O SI
        // }

        // if (String.IsNullOrEmpty(descripcion) == false)
        // {
        //     //INGRESA SI ESCRIBIO SI O SI 
        // }

        string resultado = "";

        if (!String.IsNullOrEmpty(descripcion))
        {
            descripcion = descripcion.ToUpper();
            //INGRESA SI ESCRIBIO SI O SI 

            //2- VERIFICAR SI ESTA EDITANDO O CREANDO NUEVO REGISTRO
            if (tipoEjercicioID == 0)
            {
                //3- VERIFICAMOS SI EXISTE EN BASE DE DATOS UN REGISTRO CON LA MISMA DESCRIPCION
                //PARA REALIZAR ESA VERIFICACION BUSCAMOS EN EL CONTEXTO, ES DECIR EN BASE DE DATOS 
                //SI EXISTE UN REGISTRO CON ESA DESCRIPCION  
                var existeTipoEjercicio = _context.TipoEjercicios.Where(t => t.Descripcion == descripcion).Count();
                if (existeTipoEjercicio == 0)
                {
                    //4- GUARDAR EL TIPO DE EJERCICIO
                    var tipoEjercicio = new TipoEjercicio
                    {
                        Descripcion = descripcion,
                        Met = metDecimal
                    };
                    _context.Add(tipoEjercicio);
                    _context.SaveChanges();
                }
                else
                {
                    resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                }
            }
            else
            {
                //QUIERE DECIR QUE VAMOS A EDITAR EL REGISTRO
                var tipoEjercicioEditar = _context.TipoEjercicios.Where(t => t.TipoEjercicioID == tipoEjercicioID).SingleOrDefault();
                if (tipoEjercicioEditar != null)
                {
                    //BUSCAMOS EN LA TABLA SI EXISTE UN REGISTRO CON EL MISMO NOMBRE PERO QUE EL ID SEA DISTINTO AL QUE ESTAMOS EDITANDO
                    var existeTipoEjercicio = _context.TipoEjercicios.Where(t => t.Descripcion == descripcion && t.TipoEjercicioID != tipoEjercicioID).Count();
                    if (existeTipoEjercicio == 0)
                    {
                        //QUIERE DECIR QUE EL ELEMENTO EXISTE Y ES CORRECTO ENTONCES CONTINUAMOS CON EL EDITAR
                        tipoEjercicioEditar.Descripcion = descripcion;
                        tipoEjercicioEditar.Met = metDecimal;
                        _context.SaveChanges();
                    }
                    else
                    {
                        resultado = "YA EXISTE UN REGISTRO CON LA MISMA DESCRIPCIÓN";
                    }
                }
            }
        }
        else
        {
            resultado = "DEBE INGRESAR UNA DESCRIPCIÓN.";
        }

        return Json(resultado);
    }

    public JsonResult EliminarTipoEjercicio(int tipoEjercicioID)
    {
        bool eliminado = false;

        //BUSCAR SI EXISTEN EJERCICIOS CARGADOS
        var existeEjercicio = _context.EjerciciosFisicos.Where(t => t.TipoEjercicioID == tipoEjercicioID).Count();
        if (existeEjercicio == 0)
        {
            var tipoEjercicio = _context.TipoEjercicios.Find(tipoEjercicioID);
            _context.Remove(tipoEjercicio);
            _context.SaveChanges();
            eliminado = true;
        }

        return Json(eliminado);
    }
}

EzpeletaNetCore8/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EzpeletaNetCore8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EzpeletaNetCore8.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/fontawesome/css/all.min.css" />

</head>

<body>

    @if (SignInManager.IsSignedIn(User))
    {


        <div class="d-flex" id="wrapper">
            <!-- Sidebar-->
            <div class="border-end bg-white" id="sidebar-wrapper" style="background-color: #d1e7dd !important;">
                <div class="sidebar-heading border-bottom bg-success text-white">Movimiento Activo</div>
                <div class="list-group list-group-flush">
                    @if (User.IsInRole("ADMINISTRADOR"))
                    {
                        <a class="list-group-item list-group-item-action list-group-item-success p-3" href="~/Eventos/Index"><i
                                class="fa-solid fa-list-check"></i> Eventos</a>
                        <a class="list-group-item list-group-item-action list-group-item-success p-3"
                            href="~/TipoEjercicios/Index"><i class="fa-solid fa-list-check"></i> Tipo de Ejercicios</a>
                    }
                    <a class="list-group-item list-group-item-action list-group-item-success p-3" href="~/Home/Index"><i
                            class="fa-solid fa-table-columns"></i> Panel General</a>

                    <a class="list-group-item list-group-item-action list-group-item-success p-3" href="~/Lugares/Index"><i
                            class="fa-solid fa-list-check"></i> Lugares</a>

                    <a class="list-group-item list-group-item-action list-group-item-success p-3"
                        href="~/EjerciciosFisicos/Index"><i class="fa-solid fa-ranking-star"></i> Ejercicios Físicos</a>
                    <a class="list-group-item list-group-item-action list-group-item-success p-3"
                        href="~/EjerciciosFisicos/EjerciciosPorTipo"><i class="fa-solid fa-file-text"></i> Informe
                        Ejercicios 1</a>
                    <a class="list-group-item list-group-item-action list-group-item-success p-3"
                        href="~/EjerciciosFisicos/EjerciciosPorLugar"><i class="fa-solid fa-file-text"></i> Informe
                        Ejercicios 2</a>
                    <a class="list-group-item list-group-item-action list-group-item-success p-3"
                        href="~/EjerciciosFisicos/InformeGeneral"><i class="fa-solid fa-file-text"></i> Informe Ejercicios
                        3</a>
                </div>
            </div>
            <!-- Page content wrapper-->
            <div id="page-content-wrapper">
                <!-- Top navigation-->
                <nav class="navbar navbar-expand-lg navbar-success bg-success border-bottom">
                    <div class="container-fluid">
                        <button class="btn btn-success" id="sidebarToggle"><i class="fa-solid fa-bars"></i></button>
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation"><span
                                class="navbar-toggler-icon"></span></button>
                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                                <partial name="_LoginPartial" />
                            </ul>
                        </div>
                    </div>
                </nav>
                <!-- Page content-->
                <div class="container-fluid">
                    <main role="main" class="mt-3 pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="container-fluid">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/js/jspdf/jspdf.min.js"></script>
    <script src="~/js/jspdf/jspdf.debug.js"></script>
    <script src="~/js/jspdf/jspdf.plugin.autotable.js"></script>

    <script src="~/js/scripts.js"></script>
    <script src="~/fontawesome/js/all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

EzpeletaNetCore8/Views/Shared/_LayoutRespaldo.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EzpeletaNetCore8</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EzpeletaNetCore8.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EzpeletaNetCore8</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoEjercicios" asp-action="Index">Tipo de Ejercicios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EzpeletaNetCore8 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>